### PR TITLE
add caribbean currencies

### PR DESCRIPTION
**Pull request by islandbitcoin**

### CODE REVIEW

**Comment by islandbitcoin** [comment]
> If I understand correctly, this change only adds price data to the UI? It does not allow users to denominate their account in another currency?
> 
> Also, do you know if this backfills with historical price data for each of these currencies? or does this just allow querying for current price data?

correct. its just a display currency. Their wallets will always be denominated in USD or BTC.

It does not backfill for historical price, this is only for real-time conversion on the Home Screen. The historical chart is in USD.

**Comment by islandbitcoin** [comment]
I don't think I have the format correct for realtime.config

**Comment by brh28** [comment]
What documentation have you seen for this? How did you know to update `Values.realtime.config` with the values provided?

**Comment by brh28** [comment]
> What documentation have you seen for this? How did you know to update `Values.realtime.config` with the values provided?

From Arvin at Galoy:

```
Yup that's a price server thing
https://t.co/oajegdSByI
From github.com
This is the relevant config here in the repo
https://t.co/Pi4QPw16Nz
From github.com
And I think we inject all our currencies via an override of this entry in charts
❤️

thx man
```

**Pull request closed without merging**
